### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by bjesus** [Kaik/gnome-shell-services-panel#1]
I'm trying to configure the plugin to work with my daemons, but I couldn't get it to work.

What's `command` in the context of a service? Obviously I have both `systemctl start nginx` and `systemctl stop nginx` for example. What's the command then?

Thanks!

**Comment by Kaik** [comment]
Hi, at this moment it is only a conception - it shows each setting "object" in area but it's settings does not yet have a meaning, apart from label https://github.com/Kaik/gnome-shell-services-panel/blob/master/extension.js#L65 It will probably be just service name and commands will be hardcoded (on/off - restart - log/service status) all of this not yet implemented. I do not know if this is possible with PopupMenu.PopupSwitchMenuItem so... I will look on it soon and see what I can do to make it work.

**Comment by bjesus** [comment]
Hi,
check this: https://github.com/bjesus/services-panel
